-- AlterTable
ALTER TABLE `companies` ADD COLUMN `gst_number` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `role_permissions` MODIFY `module` ENUM('DASHBOARD', 'USERS', 'ROLES', 'MASTERS', 'CUSTOMERS', 'ENQUIRIES', 'QUOTATIONS', 'ORDERS', 'PLANNING', 'PAYMENTS', 'CALENDAR', 'REPORTS', 'SETTINGS') NOT NULL;
