export const ROUTES = {
  login: '/login',
  dashboard: '/',
  enquiries: '/enquiries',
  quotations: '/quotations',
  orders: '/orders',
  paymentTracker: '/payment-tracker',
  calendar: '/calendar',
  // Rent — a standalone workflow, not part of the enquiry-to-order chain ("md files/Stock/stock.md" §1).
  rent: '/rent',
  rentPersons: '/rent/persons',
  rentItems: '/rent/items',
  rentStockOuts: '/rent/stock-outs',
  rentReturns: '/rent/returns',
  rentPayments: '/rent/payments',
  rentReports: '/rent/reports',
  customers: '/customers',
  masters: '/masters',
  mastersUsers: '/masters?tab=users',
  mastersRoles: '/masters?tab=roles',
  reports: '/reports',
} as const;
