-- AlterTable
ALTER TABLE `enquiries` MODIFY `status` ENUM('PENDING', 'APPOINTMENT_FIXED', 'FOLLOW_UP', 'QUOTATION_TO_SHARE', 'QUOTATION_SHARED', 'ORDER_CONFIRMED', 'ORDER_LOST') NOT NULL DEFAULT 'PENDING';
